
backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "students"
    label: "Students"
    folder: "students"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Subject", name: "subject", widget: "string" }
      - { label: "Progress", name: "progress", widget: "string" }
      - { label: "Homework Link", name: "homework_link", widget: "string" }
